import Payment from '../models/Payment.js';
import Tenant from '../models/Tenant.js';
import SystemConfig from '../models/SystemConfig.js';

/**
 * Generate monthly rent payments for all active tenants
 * @param {Object} options - Generation options
 * @param {String} options.month - Month (01-12)
 * @param {Number} options.year - Year
 * @param {Number} options.lateFeePercentage - Late fee percentage
 * @param {Number} options.gracePeriodDays - Grace period in days
 * @returns {Object} Result with generated payments count and errors
 */
export async function generateMonthlyRent(options = {}) {
  const {
    month,
    year,
    lateFeePercentage = 5,
    gracePeriodDays = 5
  } = options;

  const targetMonth = month || String(new Date().getMonth() + 1).padStart(2, '0');
  const targetYear = year || new Date().getFullYear();

  try {
    // Get all active tenants with houses
    const tenants = await Tenant.find({
      status: 'active',
      house: { $ne: null }
    }).populate('house');

    const generatedPayments = [];
    const errors = [];

    for (const tenant of tenants) {
      if (!tenant.house) continue;

      // Check if payment already exists for this month/year
      const existingPayment = await Payment.findOne({
        tenant: tenant._id,
        house: tenant.house._id,
        month: targetMonth,
        year: targetYear
      });

      if (existingPayment) {
        errors.push(`Payment already exists for ${tenant.firstName} ${tenant.lastName} - ${targetMonth}/${targetYear}`);
        continue;
      }

      // Calculate due date (first of the month)
      const dueDate = new Date(targetYear, parseInt(targetMonth) - 1, 1);

      // Get previous month's deficit to carry forward
      let carriedForward = 0;
      const prevMonth = parseInt(targetMonth) - 1;
      const prevYear = prevMonth === 0 ? targetYear - 1 : targetYear;
      const prevMonthStr = prevMonth === 0 ? '12' : String(prevMonth).padStart(2, '0');

      const prevPayment = await Payment.findOne({
        tenant: tenant._id,
        house: tenant.house._id,
        month: prevMonthStr,
        year: prevYear
      }).sort({ createdAt: -1 });

      if (prevPayment && prevPayment.deficit > 0) {
        carriedForward = prevPayment.deficit;
      }

      // Calculate expected amount (rent + carried forward deficit)
      const expectedAmount = tenant.house.rentAmount + carriedForward;

      // Calculate late fee if past due date + grace period
      const today = new Date();
      const lateFeeDate = new Date(dueDate);
      lateFeeDate.setDate(lateFeeDate.getDate() + gracePeriodDays);

      let lateFee = 0;
      let status = 'pending';

      if (today > lateFeeDate) {
        lateFee = (expectedAmount * lateFeePercentage) / 100;
        status = 'overdue';
      }

      const payment = new Payment({
        tenant: tenant._id,
        house: tenant.house._id,
        amount: expectedAmount,
        expectedAmount: expectedAmount,
        paidAmount: 0,
        deficit: expectedAmount,
        carriedForward: carriedForward,
        dueDate: dueDate,
        paymentDate: today,
        month: targetMonth,
        year: targetYear,
        status: status,
        lateFee: lateFee,
        isAutoGenerated: true,
        autoGeneratedDate: today
      });

      await payment.save();
      generatedPayments.push(payment);
    }

    // Update last generated date in config
    const config = await SystemConfig.getConfig();
    if (config.automation?.rentGeneration) {
      config.automation.rentGeneration.lastGenerated = {
        month: targetMonth,
        year: targetYear
      };
      await config.save();
    }

    return {
      success: true,
      generated: generatedPayments.length,
      errors: errors.length,
      details: errors,
      month: targetMonth,
      year: targetYear
    };
  } catch (error) {
    console.error('Error generating monthly rent:', error);
    return {
      success: false,
      error: error.message,
      generated: 0,
      errors: 0
    };
  }
}

/**
 * Check if rent should be generated automatically based on configuration
 */
export async function checkAndGenerateRent() {
  try {
    const config = await SystemConfig.getConfig();
    const automation = config.automation?.rentGeneration;

    if (!automation || !automation.enabled) {
      return { shouldGenerate: false, reason: 'Automation disabled' };
    }

    const now = new Date();
    const currentMonth = String(now.getMonth() + 1).padStart(2, '0');
    const currentYear = now.getFullYear();
    const currentDay = now.getDate();

    // Check if we should generate for this month
    const lastGenerated = automation.lastGenerated;
    if (lastGenerated && 
        lastGenerated.month === currentMonth && 
        lastGenerated.year === currentYear) {
      return { shouldGenerate: false, reason: 'Already generated for this month' };
    }

    // Check if it's the right day
    if (currentDay !== automation.dayOfMonth) {
      return { shouldGenerate: false, reason: `Not generation day (day ${automation.dayOfMonth})` };
    }

    // Get late fee settings
    const lateFeeConfig = config.automation?.lateFee || {};
    const lateFeePercentage = lateFeeConfig.percentage || 5;
    const gracePeriodDays = lateFeeConfig.gracePeriodDays || 5;

    // Generate rent
    const result = await generateMonthlyRent({
      month: currentMonth,
      year: currentYear,
      lateFeePercentage,
      gracePeriodDays
    });

    return {
      shouldGenerate: true,
      generated: result.generated,
      errors: result.errors
    };
  } catch (error) {
    console.error('Error checking rent generation:', error);
    return {
      shouldGenerate: false,
      error: error.message
    };
  }
}

