import mongoose from 'mongoose';

const paymentSchema = new mongoose.Schema({
  tenant: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Tenant',
    required: true
  },
  house: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'House',
    required: true
  },
  amount: {
    type: Number,
    required: true,
    min: 0
  },
  expectedAmount: {
    type: Number,
    min: 0
  },
  paidAmount: {
    type: Number,
    min: 0
  },
  deficit: {
    type: Number,
    default: 0,
    min: 0
  },
  carriedForward: {
    type: Number,
    default: 0,
    min: 0
  },
  paymentDate: {
    type: Date,
    required: true,
    default: Date.now
  },
  dueDate: {
    type: Date,
    required: true
  },
  paymentMethod: {
    type: String,
    enum: ['cash', 'check', 'bank_transfer', 'online', 'mobile_money', 'equity_bank', 'other'],
    default: 'cash'
  },
  status: {
    type: String,
    enum: ['pending', 'paid', 'overdue', 'partial'],
    default: 'pending'
  },
  month: {
    type: String,
    required: true
  },
  year: {
    type: Number,
    required: true
  },
  notes: {
    type: String,
    trim: true
  },
  lateFee: {
    type: Number,
    default: 0,
    min: 0
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  autoGeneratedDate: {
    type: Date
  },
  transactionId: {
    type: String,
    trim: true,
    sparse: true
  },
  referenceNumber: {
    type: String,
    trim: true
  },
  receivedFrom: {
    type: String,
    trim: true
  },
  houseNumber: {
    type: String,
    trim: true
  },
  paymentSource: {
    type: String,
    enum: ['manual', 'webhook', 'api', 'bank_transfer', 'mobile_money', 'paybill', 'mpesa_stk', 'equity_bank'],
    default: 'manual'
  },
  receiptNumber: {
    type: String,
    trim: true,
    unique: true,
    sparse: true
  }
}, {
  timestamps: true
});

export default mongoose.model('Payment', paymentSchema);

